# General
base: 'base_synth.yml'
bre_lambda: 0
recon_lambda: 0
actdiff_lambda: 0

# Masks all data in the training set only.
dataset:
  train:
    SyntheticDataset2:
        mask_all: True

# Model
model:
  UNet:
    img_size: 28
    nc: 16
    mode: 'unet'
